/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import estructures.linkedList.Player;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import managers.Master;

/**
 *
 * @author JohnBarbosa
 */
public class Game extends javax.swing.JFrame {
    
    Master m;

    /**
     * Creates new form Game
     */
    public Game(Master m) {
        this.m = m;
        Player p;
        for(int i = 0; i < m.getPlayers().length(); i++){
            p = (Player) m.getPlayers().getCourrent();
            System.out.println("Nombre del jugador: " + p.getPlayerName());
            m.getPlayers().next();
        }
        
        
        initComponents();
        loadTable();

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    public void render(Graphics g){
        g.drawRect(10, 10, 50, 50);
    }

    private void loadTable() {

        //lTable.setIcon(new ImageIcon(new javax.swing.ImageIcon("./resources/monopoly-table.jpg").getImage().getScaledInstance(746, 746, Image.SCALE_SMOOTH)));
        //lTable.setBorder(BorderFactory.createLineBorder(Color.black));
        pTable.repaint();

        Icon icon = new ImageIcon(new javax.swing.ImageIcon("./resources/gfx/monopoly-table.jpg").getImage().getScaledInstance(746, 746, Image.SCALE_SMOOTH));
        JLabel label = new JLabel(icon);
        
        

        pTable.add(label);
        Dimension size = label.getPreferredSize();
        label.setBounds(0, 0, size.width, size.height);
        label.setBorder(BorderFactory.createLineBorder(Color.black));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTable = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Table");
        setResizable(false);

        javax.swing.GroupLayout pTableLayout = new javax.swing.GroupLayout(pTable);
        pTable.setLayout(pTableLayout);
        pTableLayout.setHorizontalGroup(
            pTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        pTableLayout.setVerticalGroup(
            pTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addComponent(pTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pTable;
    // End of variables declaration//GEN-END:variables
}
